import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
export function SummaryPanel({ summary, stopped }) {
    return (_jsxs("section", { className: "block", "aria-label": "\u4ECA\u56DE\u306E\u7D50\u679C", children: [_jsx("h2", { children: "\u4ECA\u56DE\u306E\u7D50\u679C" }), !summary ? (_jsx("p", { className: "empty", children: stopped ? '1コードぶん弾き終わる前に止まりました。' : '練習が終わるとここに結果が出ます。' })) : (_jsxs(_Fragment, { children: [summary.rhythm ? (_jsxs("div", { className: "stats", children: [_jsxs("div", { children: [_jsxs("b", { children: [summary.rhythm.played, "/", summary.rhythm.expected] }), _jsxs("span", { children: ["\u9CF4\u3089\u305B\u305F\u30B9\u30C8\u30ED\u30FC\u30AF", summary.rhythm.extra ? ` (余分 ${summary.rhythm.extra})` : ''] })] }), _jsxs("div", { children: [_jsx("b", { children: summary.rhythm.meanAbs == null ? '…' : `${Math.round(summary.rhythm.meanAbs)}ms` }), _jsx("span", { children: "\u30B9\u30C8\u30ED\u30FC\u30AF\u306E\u5E73\u5747\u30BA\u30EC" })] }), _jsxs("div", { children: [_jsx("b", { children: summary.rhythm.evenness }), _jsx("span", { children: "\u5F37\u3055\u306E\u7C92" })] })] })) : null, _jsxs("div", { className: "stats", style: summary.rhythm ? { marginTop: 12 } : undefined, children: [summary.chordJudged && (_jsxs("div", { children: [_jsxs("b", { children: [summary.okN, "/", summary.total] }), _jsx("span", { children: "\u30B3\u30FC\u30C9\u304C\u5408\u3063\u305F\u56DE\u6570" })] })), _jsxs("div", { children: [_jsx("b", { children: summary.meanAbs == null ? '…' : `${Math.round(summary.meanAbs)}ms` }), _jsx("span", { children: "\u30C1\u30A7\u30F3\u30B8\u306E\u5E73\u5747\u30BA\u30EC" })] }), _jsxs("div", { children: [_jsx("b", { children: trendLabel(summary.median) }), _jsxs("span", { children: ["\u30BA\u30EC\u306E\u50BE\u5411", summary.median == null ? '' : ` (${summary.median > 0 ? '+' : ''}${Math.round(summary.median)}ms)`] })] })] }), _jsx("ul", { className: "list", children: summary.perChord.map((p) => (_jsxs("li", { children: [_jsxs("span", { children: [_jsx("b", { children: p.chord }), " ", p.notes] }), _jsxs("span", { children: [p.ok, "/", p.n] })] }, p.chord))) })] }))] }));
}
function trendLabel(med) {
    if (med == null)
        return '…';
    if (Math.abs(med) < 15)
        return 'ほぼ中央';
    return med > 0 ? '遅め' : '早め';
}
